// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9gEeksYS11GZdc0mpsBxCm0kmafqpHg',
    appId: '1:400047742252:web:49112c697c7a1072fa2089',
    messagingSenderId: '400047742252',
    projectId: 'softeng-pawfectmatch1',
    authDomain: 'softeng-pawfectmatch1.firebaseapp.com',
    storageBucket: 'softeng-pawfectmatch1.appspot.com',
    measurementId: 'G-VQWFJQH2WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGHzSEr9EnBSg2Y1ApRPkCHHksP9zb9u8',
    appId: '1:400047742252:android:9125c472b87806c1fa2089',
    messagingSenderId: '400047742252',
    projectId: 'softeng-pawfectmatch1',
    storageBucket: 'softeng-pawfectmatch1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPoblkdCklOBI8OUeA6-0FqjhEcg1ekXo',
    appId: '1:400047742252:ios:089f30435ba39817fa2089',
    messagingSenderId: '400047742252',
    projectId: 'softeng-pawfectmatch1',
    storageBucket: 'softeng-pawfectmatch1.appspot.com',
    iosBundleId: 'com.example.pawfectmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPoblkdCklOBI8OUeA6-0FqjhEcg1ekXo',
    appId: '1:400047742252:ios:089f30435ba39817fa2089',
    messagingSenderId: '400047742252',
    projectId: 'softeng-pawfectmatch1',
    storageBucket: 'softeng-pawfectmatch1.appspot.com',
    iosBundleId: 'com.example.pawfectmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9gEeksYS11GZdc0mpsBxCm0kmafqpHg',
    appId: '1:400047742252:web:da9ae4593d5cee41fa2089',
    messagingSenderId: '400047742252',
    projectId: 'softeng-pawfectmatch1',
    authDomain: 'softeng-pawfectmatch1.firebaseapp.com',
    storageBucket: 'softeng-pawfectmatch1.appspot.com',
    measurementId: 'G-1X7KQ84CVJ',
  );

}