// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRWYn8TMWMFM0QxrWi-PnZHScnme_N9fU',
    appId: '1:247180526908:web:9f6769c43086574e048a39',
    messagingSenderId: '247180526908',
    projectId: 'softeng-pawfectmatch',
    authDomain: 'softeng-pawfectmatch.firebaseapp.com',
    storageBucket: 'softeng-pawfectmatch.appspot.com',
    measurementId: 'G-6LMXP7351Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1j32hlrEpu9TyuKOJuWQ77-DHZObjQe4',
    appId: '1:247180526908:android:5b82e34a44079345048a39',
    messagingSenderId: '247180526908',
    projectId: 'softeng-pawfectmatch',
    storageBucket: 'softeng-pawfectmatch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrA8CV2Pd3iksOsKxT8yNMoJyQYLzkNEY',
    appId: '1:247180526908:ios:60d5e6141e29d722048a39',
    messagingSenderId: '247180526908',
    projectId: 'softeng-pawfectmatch',
    storageBucket: 'softeng-pawfectmatch.appspot.com',
    iosBundleId: 'com.example.pawfectmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrA8CV2Pd3iksOsKxT8yNMoJyQYLzkNEY',
    appId: '1:247180526908:ios:60d5e6141e29d722048a39',
    messagingSenderId: '247180526908',
    projectId: 'softeng-pawfectmatch',
    storageBucket: 'softeng-pawfectmatch.appspot.com',
    iosBundleId: 'com.example.pawfectmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRWYn8TMWMFM0QxrWi-PnZHScnme_N9fU',
    appId: '1:247180526908:web:1627cb175e8eab09048a39',
    messagingSenderId: '247180526908',
    projectId: 'softeng-pawfectmatch',
    authDomain: 'softeng-pawfectmatch.firebaseapp.com',
    storageBucket: 'softeng-pawfectmatch.appspot.com',
    measurementId: 'G-C4CLKBSXH5',
  );

}